rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        web:
#          cors: DEBUG

sentry:
  dsn: https://f93f0fccdb8ea4ab00379f95df35c253@o4507203302653952.ingest.de.sentry.io/4507203346890832
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0


