rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

spring:
  jpa:
    show-sql: true
    generate-ddl: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          cors: DEBUG